name: flutter_chess_board
description: A Chessboard Widget for Flutter. The widget also maintains game state and gives callbacks for game events.
version: 0.9.4
author: Deven Joshi <deven9852@gmail.com>

homepage: https://www.github.com/deven98/flutter_chess_board

dependencies:
  chess: ">=0.6.5 <1.0.0"
  chess_vectors_flutter: ">=1.0.6 <2.0.0"
  scoped_model: ">=1.0.0 <2.0.0"

  flutter:
    sdk: flutter

environment:
    sdk: ">2.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/chess_board.png
    - images/brown_board.png
    - images/2.0x/brown_board.png
    - images/3.0x/brown_board.png
    - images/orange_board.png
    - images/2.0x/orange_board.png
    - images/3.0x/orange_board.png
    - images/green_board.png
    - images/2.0x/green_board.png
    - images/3.0x/green_board.png
    - images/dark_brown_board.png
    - images/2.0x/dark_brown_board.png
    - images/3.0x/dark_brown_board.png
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
